// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaign_input_sessions.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
)

const deleteInputSession = `-- name: DeleteInputSession :exec
DELETE FROM telegram_input_sessions
WHERE telegram_user_id = $1
`

func (q *Queries) DeleteInputSession(ctx context.Context, telegramUserID int64) error {
	_, err := q.db.ExecContext(ctx, deleteInputSession, telegramUserID)
	return err
}

const getInputSession = `-- name: GetInputSession :one
SELECT telegram_user_id, flow, step, payload, expires_at, created_at, updated_at
FROM telegram_input_sessions
WHERE telegram_user_id = $1
`

func (q *Queries) GetInputSession(ctx context.Context, telegramUserID int64) (TelegramInputSession, error) {
	row := q.db.QueryRowContext(ctx, getInputSession, telegramUserID)
	var i TelegramInputSession
	err := row.Scan(
		&i.TelegramUserID,
		&i.Flow,
		&i.Step,
		&i.Payload,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInputSession = `-- name: UpsertInputSession :one
INSERT INTO telegram_input_sessions (
    telegram_user_id,
    flow,
    step,
    payload,
    expires_at,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4::jsonb, $5, NOW(), NOW())
ON CONFLICT (telegram_user_id) DO UPDATE SET
    flow = EXCLUDED.flow,
    step = EXCLUDED.step,
    payload = EXCLUDED.payload,
    expires_at = EXCLUDED.expires_at,
    updated_at = NOW()
RETURNING telegram_user_id, flow, step, payload, expires_at, created_at, updated_at
`

type UpsertInputSessionParams struct {
	TelegramUserID int64
	Flow           string
	Step           string
	Column4        json.RawMessage
	ExpiresAt      sql.NullTime
}

func (q *Queries) UpsertInputSession(ctx context.Context, arg UpsertInputSessionParams) (TelegramInputSession, error) {
	row := q.db.QueryRowContext(ctx, upsertInputSession,
		arg.TelegramUserID,
		arg.Flow,
		arg.Step,
		arg.Column4,
		arg.ExpiresAt,
	)
	var i TelegramInputSession
	err := row.Scan(
		&i.TelegramUserID,
		&i.Flow,
		&i.Step,
		&i.Payload,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
