// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaign_snapshots.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createCampaignSnapshot = `-- name: CreateCampaignSnapshot :one
INSERT INTO ad_campaign_snapshots (
    campaign_id,
    snapshot_at,
    total_views,
    remaining_views,
    daily_growth,
    estimated_close_date,
    created_at
) VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id
`

type CreateCampaignSnapshotParams struct {
	CampaignID         int64
	SnapshotAt         time.Time
	TotalViews         int64
	RemainingViews     sql.NullInt64
	DailyGrowth        sql.NullInt64
	EstimatedCloseDate sql.NullTime
}

func (q *Queries) CreateCampaignSnapshot(ctx context.Context, arg CreateCampaignSnapshotParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCampaignSnapshot,
		arg.CampaignID,
		arg.SnapshotAt,
		arg.TotalViews,
		arg.RemainingViews,
		arg.DailyGrowth,
		arg.EstimatedCloseDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createCampaignSnapshotVideo = `-- name: CreateCampaignSnapshotVideo :exec
INSERT INTO ad_campaign_snapshot_videos (
    snapshot_id,
    position,
    video_id,
    name,
    publish_date,
    views,
    url,
    views_updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateCampaignSnapshotVideoParams struct {
	SnapshotID     int64
	Position       int32
	VideoID        string
	Name           string
	PublishDate    time.Time
	Views          int64
	Url            string
	ViewsUpdatedAt time.Time
}

func (q *Queries) CreateCampaignSnapshotVideo(ctx context.Context, arg CreateCampaignSnapshotVideoParams) error {
	_, err := q.db.ExecContext(ctx, createCampaignSnapshotVideo,
		arg.SnapshotID,
		arg.Position,
		arg.VideoID,
		arg.Name,
		arg.PublishDate,
		arg.Views,
		arg.Url,
		arg.ViewsUpdatedAt,
	)
	return err
}

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, campaign_id, snapshot_at, total_views, remaining_views, daily_growth, estimated_close_date, created_at
FROM ad_campaign_snapshots
WHERE campaign_id = $1
ORDER BY snapshot_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestSnapshot(ctx context.Context, campaignID int64) (AdCampaignSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getLatestSnapshot, campaignID)
	var i AdCampaignSnapshot
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SnapshotAt,
		&i.TotalViews,
		&i.RemainingViews,
		&i.DailyGrowth,
		&i.EstimatedCloseDate,
		&i.CreatedAt,
	)
	return i, err
}

const getPreviousSnapshot = `-- name: GetPreviousSnapshot :one
SELECT id, campaign_id, snapshot_at, total_views, remaining_views, daily_growth, estimated_close_date, created_at
FROM ad_campaign_snapshots
WHERE campaign_id = $1 AND snapshot_at < $2
ORDER BY snapshot_at DESC, id DESC
LIMIT 1
`

type GetPreviousSnapshotParams struct {
	CampaignID int64
	SnapshotAt time.Time
}

func (q *Queries) GetPreviousSnapshot(ctx context.Context, arg GetPreviousSnapshotParams) (AdCampaignSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getPreviousSnapshot, arg.CampaignID, arg.SnapshotAt)
	var i AdCampaignSnapshot
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SnapshotAt,
		&i.TotalViews,
		&i.RemainingViews,
		&i.DailyGrowth,
		&i.EstimatedCloseDate,
		&i.CreatedAt,
	)
	return i, err
}

const listCampaignSnapshotVideos = `-- name: ListCampaignSnapshotVideos :many
SELECT video_id, name, publish_date, views, url, views_updated_at
FROM ad_campaign_snapshot_videos
WHERE snapshot_id = $1
ORDER BY publish_date ASC, position ASC, id ASC
`

type ListCampaignSnapshotVideosRow struct {
	VideoID        string
	Name           string
	PublishDate    time.Time
	Views          int64
	Url            string
	ViewsUpdatedAt time.Time
}

func (q *Queries) ListCampaignSnapshotVideos(ctx context.Context, snapshotID int64) ([]ListCampaignSnapshotVideosRow, error) {
	rows, err := q.db.QueryContext(ctx, listCampaignSnapshotVideos, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignSnapshotVideosRow
	for rows.Next() {
		var i ListCampaignSnapshotVideosRow
		if err := rows.Scan(
			&i.VideoID,
			&i.Name,
			&i.PublishDate,
			&i.Views,
			&i.Url,
			&i.ViewsUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
