// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaign_user_settings.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getUserSettings = `-- name: GetUserSettings :one
SELECT telegram_user_id, notifications_enabled, notification_time, timezone, last_notification_sent_at, created_at, updated_at, google_email, google_refresh_token, google_connected_at, notification_interval_minutes
FROM telegram_user_settings
WHERE telegram_user_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, telegramUserID int64) (TelegramUserSetting, error) {
	row := q.db.QueryRowContext(ctx, getUserSettings, telegramUserID)
	var i TelegramUserSetting
	err := row.Scan(
		&i.TelegramUserID,
		&i.NotificationsEnabled,
		&i.NotificationTime,
		&i.Timezone,
		&i.LastNotificationSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleEmail,
		&i.GoogleRefreshToken,
		&i.GoogleConnectedAt,
		&i.NotificationIntervalMinutes,
	)
	return i, err
}

const listNotificationUsers = `-- name: ListNotificationUsers :many
SELECT users.telegram_user_id,
    COALESCE(settings.notifications_enabled, TRUE) AS notifications_enabled,
    COALESCE(settings.notification_time, $1) AS notification_time,
    COALESCE(settings.notification_interval_minutes, $2) AS notification_interval_minutes,
    COALESCE(settings.timezone, $3) AS timezone,
    settings.last_notification_sent_at,
    COALESCE(settings.created_at, NOW()) AS created_at,
    COALESCE(settings.updated_at, NOW()) AS updated_at
FROM (
    SELECT telegram_user_id FROM telegram_user_settings
    UNION
    SELECT DISTINCT telegram_user_id FROM telegram_user_channels
    UNION
    SELECT DISTINCT telegram_user_id FROM ad_campaigns WHERE closed_at IS NULL
) AS users
LEFT JOIN telegram_user_settings AS settings ON settings.telegram_user_id = users.telegram_user_id
WHERE COALESCE(settings.notifications_enabled, TRUE) = TRUE
ORDER BY users.telegram_user_id ASC
`

type ListNotificationUsersParams struct {
	NotificationTime            string
	NotificationIntervalMinutes int32
	Timezone                    string
}

type ListNotificationUsersRow struct {
	TelegramUserID              int64
	NotificationsEnabled        bool
	NotificationTime            string
	NotificationIntervalMinutes int32
	Timezone                    string
	LastNotificationSentAt      sql.NullTime
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
}

func (q *Queries) ListNotificationUsers(ctx context.Context, arg ListNotificationUsersParams) ([]ListNotificationUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationUsers, arg.NotificationTime, arg.NotificationIntervalMinutes, arg.Timezone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationUsersRow
	for rows.Next() {
		var i ListNotificationUsersRow
		if err := rows.Scan(
			&i.TelegramUserID,
			&i.NotificationsEnabled,
			&i.NotificationTime,
			&i.NotificationIntervalMinutes,
			&i.Timezone,
			&i.LastNotificationSentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
INSERT INTO telegram_user_settings (
    telegram_user_id,
    notifications_enabled,
    notification_time,
    notification_interval_minutes,
    timezone,
    last_notification_sent_at,
    created_at,
    updated_at
) VALUES ($1, TRUE, $2, $3, $4, $5, NOW(), NOW())
ON CONFLICT (telegram_user_id) DO UPDATE SET
    last_notification_sent_at = EXCLUDED.last_notification_sent_at,
    updated_at = NOW()
`

type MarkNotificationSentParams struct {
	TelegramUserID              int64
	NotificationTime            string
	NotificationIntervalMinutes int32
	Timezone                    string
	LastNotificationSentAt      sql.NullTime
}

func (q *Queries) MarkNotificationSent(ctx context.Context, arg MarkNotificationSentParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationSent,
		arg.TelegramUserID,
		arg.NotificationTime,
		arg.NotificationIntervalMinutes,
		arg.Timezone,
		arg.LastNotificationSentAt,
	)
	return err
}

const saveGoogleLink = `-- name: SaveGoogleLink :one
INSERT INTO telegram_user_settings (
    telegram_user_id,
    notifications_enabled,
    notification_time,
    notification_interval_minutes,
    timezone,
    google_email,
    google_refresh_token,
    google_connected_at,
    created_at,
    updated_at
) VALUES ($1, TRUE, $2, $3, $4, $5, $6, $7, NOW(), NOW())
ON CONFLICT (telegram_user_id) DO UPDATE SET
    google_email = EXCLUDED.google_email,
    google_refresh_token = EXCLUDED.google_refresh_token,
    google_connected_at = EXCLUDED.google_connected_at,
    updated_at = NOW()
RETURNING telegram_user_id, notifications_enabled, notification_time, timezone, last_notification_sent_at, created_at, updated_at, google_email, google_refresh_token, google_connected_at, notification_interval_minutes
`

type SaveGoogleLinkParams struct {
	TelegramUserID              int64
	NotificationTime            string
	NotificationIntervalMinutes int32
	Timezone                    string
	GoogleEmail                 sql.NullString
	GoogleRefreshToken          sql.NullString
	GoogleConnectedAt           sql.NullTime
}

func (q *Queries) SaveGoogleLink(ctx context.Context, arg SaveGoogleLinkParams) (TelegramUserSetting, error) {
	row := q.db.QueryRowContext(ctx, saveGoogleLink,
		arg.TelegramUserID,
		arg.NotificationTime,
		arg.NotificationIntervalMinutes,
		arg.Timezone,
		arg.GoogleEmail,
		arg.GoogleRefreshToken,
		arg.GoogleConnectedAt,
	)
	var i TelegramUserSetting
	err := row.Scan(
		&i.TelegramUserID,
		&i.NotificationsEnabled,
		&i.NotificationTime,
		&i.Timezone,
		&i.LastNotificationSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleEmail,
		&i.GoogleRefreshToken,
		&i.GoogleConnectedAt,
		&i.NotificationIntervalMinutes,
	)
	return i, err
}

const upsertUserSettings = `-- name: UpsertUserSettings :one
INSERT INTO telegram_user_settings (
    telegram_user_id,
    notifications_enabled,
    notification_time,
    notification_interval_minutes,
    timezone,
    google_email,
    google_refresh_token,
    google_connected_at,
    last_notification_sent_at,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, NULL, NULL, NULL, $6, NOW(), NOW())
ON CONFLICT (telegram_user_id) DO UPDATE SET
    notifications_enabled = EXCLUDED.notifications_enabled,
    notification_time = EXCLUDED.notification_time,
    notification_interval_minutes = EXCLUDED.notification_interval_minutes,
    timezone = EXCLUDED.timezone,
    last_notification_sent_at = COALESCE(EXCLUDED.last_notification_sent_at, telegram_user_settings.last_notification_sent_at),
    updated_at = NOW()
RETURNING telegram_user_id, notifications_enabled, notification_time, timezone, last_notification_sent_at, created_at, updated_at, google_email, google_refresh_token, google_connected_at, notification_interval_minutes
`

type UpsertUserSettingsParams struct {
	TelegramUserID              int64
	NotificationsEnabled        bool
	NotificationTime            string
	NotificationIntervalMinutes int32
	Timezone                    string
	LastNotificationSentAt      sql.NullTime
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) (TelegramUserSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertUserSettings,
		arg.TelegramUserID,
		arg.NotificationsEnabled,
		arg.NotificationTime,
		arg.NotificationIntervalMinutes,
		arg.Timezone,
		arg.LastNotificationSentAt,
	)
	var i TelegramUserSetting
	err := row.Scan(
		&i.TelegramUserID,
		&i.NotificationsEnabled,
		&i.NotificationTime,
		&i.Timezone,
		&i.LastNotificationSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleEmail,
		&i.GoogleRefreshToken,
		&i.GoogleConnectedAt,
		&i.NotificationIntervalMinutes,
	)
	return i, err
}
