// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const closeCampaign = `-- name: CloseCampaign :execrows
UPDATE ad_campaigns
SET status = $2,
    closed_at = $3,
    close_reason = $4,
    updated_at = NOW()
WHERE id = $1 AND closed_at IS NULL
`

type CloseCampaignParams struct {
	ID          int64
	Status      string
	ClosedAt    sql.NullTime
	CloseReason sql.NullString
}

func (q *Queries) CloseCampaign(ctx context.Context, arg CloseCampaignParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeCampaign,
		arg.ID,
		arg.Status,
		arg.ClosedAt,
		arg.CloseReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO ad_campaigns (
    telegram_user_id,
    channel_id,
    channel_title,
    keyword,
    start_date,
    timezone,
    target_views,
    columns,
    status,
    export_jwt,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb, $9, $10, NOW(), NOW())
RETURNING id, telegram_user_id, channel_id, channel_title, keyword, start_date, timezone, target_views, status, export_jwt, closed_at, close_reason, last_snapshot_at, last_total_views, last_daily_growth, estimated_close_date, created_at, updated_at, spreadsheet_id, spreadsheet_url, columns
`

type CreateCampaignParams struct {
	TelegramUserID int64
	ChannelID      string
	ChannelTitle   string
	Keyword        string
	StartDate      time.Time
	Timezone       string
	TargetViews    sql.NullInt64
	Column8        json.RawMessage
	Status         string
	ExportJwt      string
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (AdCampaign, error) {
	row := q.db.QueryRowContext(ctx, createCampaign,
		arg.TelegramUserID,
		arg.ChannelID,
		arg.ChannelTitle,
		arg.Keyword,
		arg.StartDate,
		arg.Timezone,
		arg.TargetViews,
		arg.Column8,
		arg.Status,
		arg.ExportJwt,
	)
	var i AdCampaign
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.ChannelID,
		&i.ChannelTitle,
		&i.Keyword,
		&i.StartDate,
		&i.Timezone,
		&i.TargetViews,
		&i.Status,
		&i.ExportJwt,
		&i.ClosedAt,
		&i.CloseReason,
		&i.LastSnapshotAt,
		&i.LastTotalViews,
		&i.LastDailyGrowth,
		&i.EstimatedCloseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpreadsheetID,
		&i.SpreadsheetUrl,
		&i.Columns,
	)
	return i, err
}

const getCampaignByChannelIdentity = `-- name: GetCampaignByChannelIdentity :one
SELECT id, telegram_user_id, channel_id, channel_title, keyword, start_date, timezone, target_views, status, export_jwt, closed_at, close_reason, last_snapshot_at, last_total_views, last_daily_growth, estimated_close_date, created_at, updated_at, spreadsheet_id, spreadsheet_url, columns
FROM ad_campaigns
WHERE ad_campaigns.channel_id = $1 AND ad_campaigns.keyword = $2 AND ad_campaigns.start_date = $3
ORDER BY ad_campaigns.id ASC
LIMIT 1
`

type GetCampaignByChannelIdentityParams struct {
	ChannelID string
	Keyword   string
	StartDate time.Time
}

func (q *Queries) GetCampaignByChannelIdentity(ctx context.Context, arg GetCampaignByChannelIdentityParams) (AdCampaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaignByChannelIdentity, arg.ChannelID, arg.Keyword, arg.StartDate)
	var i AdCampaign
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.ChannelID,
		&i.ChannelTitle,
		&i.Keyword,
		&i.StartDate,
		&i.Timezone,
		&i.TargetViews,
		&i.Status,
		&i.ExportJwt,
		&i.ClosedAt,
		&i.CloseReason,
		&i.LastSnapshotAt,
		&i.LastTotalViews,
		&i.LastDailyGrowth,
		&i.EstimatedCloseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpreadsheetID,
		&i.SpreadsheetUrl,
		&i.Columns,
	)
	return i, err
}

const getCampaignByExportJWT = `-- name: GetCampaignByExportJWT :one
SELECT id, telegram_user_id, channel_id, channel_title, keyword, start_date, timezone, target_views, status, export_jwt, closed_at, close_reason, last_snapshot_at, last_total_views, last_daily_growth, estimated_close_date, created_at, updated_at, spreadsheet_id, spreadsheet_url, columns
FROM ad_campaigns
WHERE export_jwt = $1
`

func (q *Queries) GetCampaignByExportJWT(ctx context.Context, exportJwt string) (AdCampaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaignByExportJWT, exportJwt)
	var i AdCampaign
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.ChannelID,
		&i.ChannelTitle,
		&i.Keyword,
		&i.StartDate,
		&i.Timezone,
		&i.TargetViews,
		&i.Status,
		&i.ExportJwt,
		&i.ClosedAt,
		&i.CloseReason,
		&i.LastSnapshotAt,
		&i.LastTotalViews,
		&i.LastDailyGrowth,
		&i.EstimatedCloseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpreadsheetID,
		&i.SpreadsheetUrl,
		&i.Columns,
	)
	return i, err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, telegram_user_id, channel_id, channel_title, keyword, start_date, timezone, target_views, status, export_jwt, closed_at, close_reason, last_snapshot_at, last_total_views, last_daily_growth, estimated_close_date, created_at, updated_at, spreadsheet_id, spreadsheet_url, columns
FROM ad_campaigns
WHERE ad_campaigns.id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id int64) (AdCampaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaignByID, id)
	var i AdCampaign
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.ChannelID,
		&i.ChannelTitle,
		&i.Keyword,
		&i.StartDate,
		&i.Timezone,
		&i.TargetViews,
		&i.Status,
		&i.ExportJwt,
		&i.ClosedAt,
		&i.CloseReason,
		&i.LastSnapshotAt,
		&i.LastTotalViews,
		&i.LastDailyGrowth,
		&i.EstimatedCloseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpreadsheetID,
		&i.SpreadsheetUrl,
		&i.Columns,
	)
	return i, err
}

const getCampaignByIDForUser = `-- name: GetCampaignByIDForUser :one
SELECT id, telegram_user_id, channel_id, channel_title, keyword, start_date, timezone, target_views, status, export_jwt, closed_at, close_reason, last_snapshot_at, last_total_views, last_daily_growth, estimated_close_date, created_at, updated_at, spreadsheet_id, spreadsheet_url, columns
FROM ad_campaigns
WHERE ad_campaigns.id = $1 AND EXISTS (
    SELECT 1
    FROM telegram_user_channels
    WHERE telegram_user_channels.telegram_user_id = $2 AND telegram_user_channels.channel_id = ad_campaigns.channel_id
)
`

type GetCampaignByIDForUserParams struct {
	ID             int64
	TelegramUserID int64
}

func (q *Queries) GetCampaignByIDForUser(ctx context.Context, arg GetCampaignByIDForUserParams) (AdCampaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaignByIDForUser, arg.ID, arg.TelegramUserID)
	var i AdCampaign
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.ChannelID,
		&i.ChannelTitle,
		&i.Keyword,
		&i.StartDate,
		&i.Timezone,
		&i.TargetViews,
		&i.Status,
		&i.ExportJwt,
		&i.ClosedAt,
		&i.CloseReason,
		&i.LastSnapshotAt,
		&i.LastTotalViews,
		&i.LastDailyGrowth,
		&i.EstimatedCloseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpreadsheetID,
		&i.SpreadsheetUrl,
		&i.Columns,
	)
	return i, err
}

const listUserCampaigns = `-- name: ListUserCampaigns :many
SELECT id, telegram_user_id, channel_id, channel_title, keyword, start_date, timezone, target_views, status, export_jwt, closed_at, close_reason, last_snapshot_at, last_total_views, last_daily_growth, estimated_close_date, created_at, updated_at, spreadsheet_id, spreadsheet_url, columns
FROM ad_campaigns
WHERE EXISTS (
    SELECT 1
    FROM telegram_user_channels
    WHERE telegram_user_channels.telegram_user_id = $1 AND telegram_user_channels.channel_id = ad_campaigns.channel_id
)
ORDER BY ad_campaigns.created_at DESC, ad_campaigns.id DESC
`

func (q *Queries) ListUserCampaigns(ctx context.Context, telegramUserID int64) ([]AdCampaign, error) {
	rows, err := q.db.QueryContext(ctx, listUserCampaigns, telegramUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdCampaign
	for rows.Next() {
		var i AdCampaign
		if err := rows.Scan(
			&i.ID,
			&i.TelegramUserID,
			&i.ChannelID,
			&i.ChannelTitle,
			&i.Keyword,
			&i.StartDate,
			&i.Timezone,
			&i.TargetViews,
			&i.Status,
			&i.ExportJwt,
			&i.ClosedAt,
			&i.CloseReason,
			&i.LastSnapshotAt,
			&i.LastTotalViews,
			&i.LastDailyGrowth,
			&i.EstimatedCloseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SpreadsheetID,
			&i.SpreadsheetUrl,
			&i.Columns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaignAfterSnapshot = `-- name: UpdateCampaignAfterSnapshot :exec
UPDATE ad_campaigns
SET status = $2,
    closed_at = $3,
    close_reason = $4,
    last_snapshot_at = $5,
    last_total_views = $6,
    last_daily_growth = $7,
    estimated_close_date = $8,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCampaignAfterSnapshotParams struct {
	ID                 int64
	Status             string
	ClosedAt           sql.NullTime
	CloseReason        sql.NullString
	LastSnapshotAt     sql.NullTime
	LastTotalViews     int64
	LastDailyGrowth    sql.NullInt64
	EstimatedCloseDate sql.NullTime
}

func (q *Queries) UpdateCampaignAfterSnapshot(ctx context.Context, arg UpdateCampaignAfterSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, updateCampaignAfterSnapshot,
		arg.ID,
		arg.Status,
		arg.ClosedAt,
		arg.CloseReason,
		arg.LastSnapshotAt,
		arg.LastTotalViews,
		arg.LastDailyGrowth,
		arg.EstimatedCloseDate,
	)
	return err
}

const updateCampaignColumns = `-- name: UpdateCampaignColumns :exec
UPDATE ad_campaigns
SET columns = $2::jsonb,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCampaignColumnsParams struct {
	ID      int64
	Column2 json.RawMessage
}

func (q *Queries) UpdateCampaignColumns(ctx context.Context, arg UpdateCampaignColumnsParams) error {
	_, err := q.db.ExecContext(ctx, updateCampaignColumns, arg.ID, arg.Column2)
	return err
}

const updateCampaignSpreadsheet = `-- name: UpdateCampaignSpreadsheet :exec
UPDATE ad_campaigns
SET spreadsheet_id = $2,
    spreadsheet_url = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCampaignSpreadsheetParams struct {
	ID             int64
	SpreadsheetID  sql.NullString
	SpreadsheetUrl sql.NullString
}

func (q *Queries) UpdateCampaignSpreadsheet(ctx context.Context, arg UpdateCampaignSpreadsheetParams) error {
	_, err := q.db.ExecContext(ctx, updateCampaignSpreadsheet, arg.ID, arg.SpreadsheetID, arg.SpreadsheetUrl)
	return err
}

const updateCampaignTarget = `-- name: UpdateCampaignTarget :exec
UPDATE ad_campaigns
SET target_views = $2,
    status = $3,
    closed_at = $4,
    close_reason = $5,
    estimated_close_date = $6,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCampaignTargetParams struct {
	ID                 int64
	TargetViews        sql.NullInt64
	Status             string
	ClosedAt           sql.NullTime
	CloseReason        sql.NullString
	EstimatedCloseDate sql.NullTime
}

func (q *Queries) UpdateCampaignTarget(ctx context.Context, arg UpdateCampaignTargetParams) error {
	_, err := q.db.ExecContext(ctx, updateCampaignTarget,
		arg.ID,
		arg.TargetViews,
		arg.Status,
		arg.ClosedAt,
		arg.CloseReason,
		arg.EstimatedCloseDate,
	)
	return err
}
