// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaign_user_channels.sql

package sqlc

import (
	"context"
)

const addUserChannel = `-- name: AddUserChannel :one
INSERT INTO telegram_user_channels (
    telegram_user_id,
    channel_id,
    channel_title,
    created_at,
    updated_at
) VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, telegram_user_id, channel_id, channel_title, created_at, updated_at
`

type AddUserChannelParams struct {
	TelegramUserID int64
	ChannelID      string
	ChannelTitle   string
}

func (q *Queries) AddUserChannel(ctx context.Context, arg AddUserChannelParams) (TelegramUserChannel, error) {
	row := q.db.QueryRowContext(ctx, addUserChannel, arg.TelegramUserID, arg.ChannelID, arg.ChannelTitle)
	var i TelegramUserChannel
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.ChannelID,
		&i.ChannelTitle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserChannel = `-- name: DeleteUserChannel :execrows
DELETE FROM telegram_user_channels
WHERE telegram_user_id = $1 AND channel_id = $2
`

type DeleteUserChannelParams struct {
	TelegramUserID int64
	ChannelID      string
}

func (q *Queries) DeleteUserChannel(ctx context.Context, arg DeleteUserChannelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserChannel, arg.TelegramUserID, arg.ChannelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserChannel = `-- name: GetUserChannel :one
SELECT id, telegram_user_id, channel_id, channel_title, created_at, updated_at
FROM telegram_user_channels
WHERE telegram_user_id = $1 AND channel_id = $2
`

type GetUserChannelParams struct {
	TelegramUserID int64
	ChannelID      string
}

func (q *Queries) GetUserChannel(ctx context.Context, arg GetUserChannelParams) (TelegramUserChannel, error) {
	row := q.db.QueryRowContext(ctx, getUserChannel, arg.TelegramUserID, arg.ChannelID)
	var i TelegramUserChannel
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.ChannelID,
		&i.ChannelTitle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserChannels = `-- name: ListUserChannels :many
SELECT id, telegram_user_id, channel_id, channel_title, created_at, updated_at
FROM telegram_user_channels
WHERE telegram_user_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListUserChannels(ctx context.Context, telegramUserID int64) ([]TelegramUserChannel, error) {
	rows, err := q.db.QueryContext(ctx, listUserChannels, telegramUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelegramUserChannel
	for rows.Next() {
		var i TelegramUserChannel
		if err := rows.Scan(
			&i.ID,
			&i.TelegramUserID,
			&i.ChannelID,
			&i.ChannelTitle,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
