// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaign_public_sessions.sql

package sqlc

import (
	"context"
	"time"
)

const createPublicSession = `-- name: CreatePublicSession :exec
INSERT INTO public_user_sessions (
    id,
    telegram_user_id,
    refresh_token_hash,
    expires_at,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, NOW(), NOW())
`

type CreatePublicSessionParams struct {
	ID               string
	TelegramUserID   int64
	RefreshTokenHash string
	ExpiresAt        time.Time
}

func (q *Queries) CreatePublicSession(ctx context.Context, arg CreatePublicSessionParams) error {
	_, err := q.db.ExecContext(ctx, createPublicSession,
		arg.ID,
		arg.TelegramUserID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
	)
	return err
}

const getPublicSession = `-- name: GetPublicSession :one
SELECT id, telegram_user_id, refresh_token_hash, expires_at, revoked_at, created_at, updated_at
FROM public_user_sessions
WHERE id = $1
`

func (q *Queries) GetPublicSession(ctx context.Context, id string) (PublicUserSession, error) {
	row := q.db.QueryRowContext(ctx, getPublicSession, id)
	var i PublicUserSession
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokePublicSession = `-- name: RevokePublicSession :exec
UPDATE public_user_sessions
SET revoked_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokePublicSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokePublicSession, id)
	return err
}

const updatePublicSession = `-- name: UpdatePublicSession :exec
UPDATE public_user_sessions
SET refresh_token_hash = $2,
    expires_at = $3,
    revoked_at = NULL,
    updated_at = NOW()
WHERE id = $1
`

type UpdatePublicSessionParams struct {
	ID               string
	RefreshTokenHash string
	ExpiresAt        time.Time
}

func (q *Queries) UpdatePublicSession(ctx context.Context, arg UpdatePublicSessionParams) error {
	_, err := q.db.ExecContext(ctx, updatePublicSession, arg.ID, arg.RefreshTokenHash, arg.ExpiresAt)
	return err
}
