// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"
)

type StatsRequest struct {
	ID           int64
	ChannelID    string
	AdWord       string
	StartDate    time.Time
	EndDate      time.Time
	HiddenVideos json.RawMessage
	FetchedAt    time.Time
}

type StatsVideo struct {
	ID          int64
	RequestID   int64
	Position    int32
	Name        string
	PublishDate time.Time
	Views       int64
	Url         string
}
