// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats_history.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"
)

const createStatsRequest = `-- name: CreateStatsRequest :one
INSERT INTO stats_requests (
    channel_id,
    ad_word,
    start_date,
    end_date,
    hidden_videos,
    fetched_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id
`

type CreateStatsRequestParams struct {
	ChannelID    string
	AdWord       string
	StartDate    time.Time
	EndDate      time.Time
	HiddenVideos json.RawMessage
	FetchedAt    time.Time
}

func (q *Queries) CreateStatsRequest(ctx context.Context, arg CreateStatsRequestParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createStatsRequest,
		arg.ChannelID,
		arg.AdWord,
		arg.StartDate,
		arg.EndDate,
		arg.HiddenVideos,
		arg.FetchedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createStatsVideo = `-- name: CreateStatsVideo :exec
INSERT INTO stats_videos (
    request_id,
    position,
    name,
    publish_date,
    views,
    url
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateStatsVideoParams struct {
	RequestID   int64
	Position    int32
	Name        string
	PublishDate time.Time
	Views       int64
	Url         string
}

func (q *Queries) CreateStatsVideo(ctx context.Context, arg CreateStatsVideoParams) error {
	_, err := q.db.ExecContext(ctx, createStatsVideo,
		arg.RequestID,
		arg.Position,
		arg.Name,
		arg.PublishDate,
		arg.Views,
		arg.Url,
	)
	return err
}
